### PR TITLE
Fix for php7.2

### LINKED ISSUE #274: Normalized sub-classes to make compatible with PHP 7.2
Abstract class processors/AbstractProcessor.php::process() is used in subclasses where its operands are incompatible in php 7.2.

public abstract function process($tokens, $void = '');

is not compatible with subclass in processors/InsertProcessor.php

public function process($tokenList, $token_category = "INSERT")

### PR DESCRIPTION
**Pull request by Hoten**
Fixes #274

### CODE REVIEW

File: src/PHPSQLParser/processors/ReplaceProcessor.php [hunk 1]
```diff
@@ -50,8 +50,8 @@
  */
 class ReplaceProcessor extends InsertProcessor {
 
-    public function process($tokenList) {
-        return parent::process($tokenList, 'REPLACE');
+    public function process($tokenList, $token_category = 'REPLACE') {
```
Comment (mikehenrty) [inline src/PHPSQLParser/processors/ReplaceProcessor.php]: might want to use camel case here, for consistency, ie `$tokenCategory`

**Comment by mikehenrty** [comment]
@greenlion any chance you could have a look at this?

File: src/PHPSQLParser/processors/ReplaceProcessor.php (hunk 1 above)
Comment (mikehenrty) [reply src/PHPSQLParser/processors/ReplaceProcessor.php]: oh, nevermind, I see now that the parent function uses `$token_category`, so you are already consistent :) sorry for the noise
